- .github/pull_request_template.md
- .github/workflows/CODEOWNERS
- .github/workflows/lint.yml
- .github/workflows/rust.yml
- README.md
* Introduces basic templates for PRs and Codeowner
* Don't lint or build on non-code changes
* Minor formatting for Workflow
> Add README and PR template.

- Cargo.toml
- README.md
- src/authentication.rs
- src/commands.rs
- src/main.rs
By default, we will have a defined human-readable output. Using -j will set the output type to JSON and print the whole underlying object. Note that the final list of fields shown by default is still subject to change.
Example output:
Adds new "-j" option for screen commands.
https://ph.wireload.net/T6409
Manually plus unit test
> Support "-j" output option

- src/commands.rs
Centers the content inside the cells. Uses Unicode ✅❌ for true/false. 
Nope
Updated tests.
> Use unicode for True/False. Center output in the table cells.

- .github/workflows/release.yml
> Update workflow release. Previous gh action used did not support apple arm 64

- src/main.rs
Fixes spelling of JSON. Old format was writing JSON in lower case:
```bash
> $ screenly --help                                                                                                                                                            
[...]
-j, --json
Enables json output
[...]
```
After PR:
```bash
> $ screenly --help                                                                                                                                                            
[...]
-j, --json
Enables JSON output
[...]
```
N/A
> Fixes formatting of JSON

- .github/workflows/release.yml
- Dockerfile
* Breaks out the docker build as a separate job in the GitHub Actions Workflow rather than a step.
* Moves to use the `musl` build.
> Attempts to fix build process

- .idea/codeStyles/codeStyleConfig.xml
- Cargo.toml
- src/authentication.rs
- src/commands.rs
- src/main.rs
Supports `inject-js` and `set-headers` commands for web assets. 
Inject-js allows setting JS injection code for web assets. Injected code will be executed during playback on the device once the asset is loaded.
set-headers similarly works on web assets setting values of custom HTTP headers.
Usage is a bit awkward but I did not come up with better syntax:
```screenly asset set-headers 01FJVFP0QVD1E5TA70SA66AJPF --header k=v --header k2=v2```
Also adds `basic-auth` command that allows setting the basic auth header by accepting username and password.
T6482
New unit tests + manual use.
> New asset commands

- src/cli.rs
Adds shortcut for setting bearer authentication in a similar way we have a command for basic auth.
For usage:
```screenly asset bearer-auth <uuid> <token>```
-
manually.
Described in the PR description
> Bearer authentication command

- Cargo.toml
- src/main.rs
Enables Sentry for CLI
https://ph.wireload.net/T7072
I called `capture_anyhow` and `panic!` in code, it was reported by Sentry:
> Enable sentry for cli

- src/cli.rs
- src/main.rs
Fixes `edge-app upload` command not working when explicit path is not passed.
Tested the command.
Unit tests for the function working with paths.
> Fix upload not working when path is not passed

- src/authentication.rs
- src/cli.rs
- src/commands/edge_app.rs
- Adds cli command edge app promote 
```
screenly edge-app promote --help        
Usage: screenly edge-app promote [OPTIONS] [PATH]
Arguments:
[PATH]  Path to the directory with the manifest. If not specified CLI will use the current working directory
Options:
-r, --revision <REVISION>  Edge app revision to promote
-h, --help                 Print help
-V, --version              Print version
```
- Adds optional commented lines for local development(with local screenly pro)
https://ph.wireload.net/T7147
Manuall on local environment and unit tests
> Adds: promote cli command.

- data/index.html
- src/commands/edge_app.rs
Ticket: https://ph.wireload.net/T7251
Edits:
- Updated index.html using updated screenly.js (settings and metadata)
- Added a default setting(username) to manifest that is used by the index.html
- Added validation that manifest and index.html do not exist on `edge-app create`
Screenshot of testing on the viewer:
> Edits: for initialized files on edge-app create

- src/commands/edge_app.rs
- src/commands/edge_app_utils.rs
Refs https://phorge.wireload.net/T7243
Update function now uses iteration 2 of edge apps, meaning changes:
- Installation instead of root id
- Settings created per app, not per revision
- Only new settings are created, old remote are not deleted
For upload there is missing a PATCH update if setting parameters has changed.
> Adds: update upload function to work with edge apps iteration 2

- src/cli.rs
- src/commands/edge_app.rs
- src/commands/edge_app_utils.rs
Refs https://phorge.wireload.net/T7243
Adds setting single secret command using global settings/secrets.
Works same as settings.
`screenly edge-app secret set key=value`
Also used fmt code command.
> Adds: settings single secret command

- src/commands/edge_app.rs
Refs https://phorge.wireload.net/T7243
Updates list settings to get settings and values from API,
and combine them in table.
Note: combining could be done with API in future, though currently it doesn't support exact this embedding.
> Update: listing settings using global settings

- src/cli.rs
- src/commands/asset.rs
- src/commands/edge_app.rs
- src/commands/mod.rs
Refs https://phorge.wireload.net/T7132
Adds versions promote command.
`screenly edge-app version promote 2  .`
Note: I now we will replace path with app_id, but this is not the point ot this pr, so added path for now.
> Adds: promote version to channel command

- src/commands/edge_app.rs
Ticket: https://phorge.wireload.net/T7239
Nginx error:
```
nginx_1                  | 2023/08/18 09:37:34 [error] 8#8: *187 lua entry thread aborted: runtime error: ...eenly/maybe_upload_file_to_s3_on_post_assets_request.lua:70: chunked request bodies not supported yet
nginx_1                  | stack traceback:
nginx_1                  | coroutine 0:
nginx_1                  |      [C]: in function 'assert'
nginx_1                  |      ...eenly/maybe_upload_file_to_s3_on_post_assets_request.lua:70: in main chunk
nginx_1                  |      access_by_lua(/etc/nginx/conf.d/appserver.conf:340):14: in main chunk, client: 192.168.80.1, server: ~^(?<subdomain>[^.]+)\.(?<domain>.+), request: "POST /api/v4/assets HTTP/1.1", host: "api.screenly.local"
nginx_1                  | 2023/08/18 …
```
> Fix: upload file against appserver

- src/commands/asset.rs
- src/commands/edge_app.rs
Fix for the error:
```
Failed to upload edge app: request error: error sending request for url (https://api.screenlyapp.com/api/v4/assets): operation timed out.
```
Edits:
- Added a client timeout equals to 1 hour. It's a value that the server allows to keep the connection on the upload endpoint.
https://phorge.wireload.net/T7309
Manually on production
> Fix: upload client timeout

- src/cli.rs
- src/commands/edge_app.rs
- src/commands/edge_app_utils.rs
- src/commands/mod.rs
Adds app_id parameter that allows to override used app id.
The path is now named argument.
Got rid of root_asset_id and revision in the manifest file. 
T7251
Tests updated
> Workflow changes

- src/commands/edge_app.rs
Used wrong function for pb - set_position is the right one to set progress, while set_length sets total length.
> Fix: progress bar set_position instead of set_length

- src/commands/edge_app.rs
This PR tweaks the URL being used to get all the settings data from the REST API when running `screenly edge-app setting list`.
There's no issue or ticket associated with this PR at the moment.
Yes, this has been tested manually.
API call after the fix:
API call before the fix:
After the fix:
```
➜  weather-app git:(main) ✗ screenly edge-app setting list
2023-08-25T00:07:03.955Z DEBUG [reqwest::connect] starting new connection: https://api.screenlyapp.com/
2023-08-25T00:07:04.285Z DEBUG [screenly::commands::edge_app] Found installation. No need to install.
2023-08-25T00:07:04.313Z DEBUG [reqwest::connect] starting new connection: https://api.screenlyapp.com/
2023-08-25T00:07:04.665Z DEBUG [reqwest::connect] starting new connection: https://api.screenlyapp.com/ …
```
> Fixes Edge App settings not displaying properly

- src/cli.rs
- src/commands/edge_app.rs
- src/commands/mod.rs
Added a new option for create command: `screenly edge-app create --in-place`.
This option allows creating edge-app using an existing edge-app directory (see Playground edge-apps for an example).
@vpetersson please add a ticket number. I can't find it.
Manually and unit tests.
> Added: a new create option for create edge-app with existing directory

- src/commands/edge_app.rs
- src/commands/mod.rs
Refs https://phorge.wireload.net/T7389
When there was an error with processing assets, cli will be timeout after 1000 seconds, while we actually now that there was an error during processing.
Fail immediately on error and print it.
> Adds: check for processing error of assets.

- src/cli.rs
- src/commands/edge_app.rs
- src/commands/mod.rs
Refs https://phorge.wireload.net/T7376
Before promote we do check if some secrets are undefined.
```
screenly edge-app version promote --revision 1
Failed to promote edge app version: Warning: these secrets are undefined: ["greeting1","greeting2"]..
```
> Adds: check undefined secrets on promote.

- src/cli.rs
- src/commands/edge_app.rs
- src/commands/mod.rs
Refs https://phorge.wireload.net/T7408
Adds list secrets command.
`screenly edge-app secret list`
```
+-------------------+----------+-------------------------------------------------------------+
| Title             | Optional | Help text                                                   |
+-------------------+----------+-------------------------------------------------------------+
| disable_analytics | No       | Whether to disable Sentry and Google Analytics integrations |
+-------------------+----------+-------------------------------------------------------------+
```
> Adds: list secrets command.

- src/commands/asset.rs
filter out edge-app-files from assets list command. Just the same way as we do it in web-console.
https://phorge.wireload.net/T7310
Manually
> Fix: filter out edge-app-files from assets list command

- src/cli.rs
- src/commands/edge_app.rs
- src/commands/edge_app_utils.rs
- src/commands/mod.rs
Refs https://phorge.wireload.net/T7415
Same as screen deletion - ask for name promt before deletion
`screenly edge-app delete`
Also updated manifest to have app_id optional -> `Option<String>`
> Adds: delete edge-app command - same as screen deletion

- src/commands/edge_app.rs
- src/commands/mod.rs
It was not informative 401 error when trying to promote revision, that doesn't exist.
Now added proper get request to versions and fails if version/revision doesn't exist
`Failed to promote edge app version: Edge App Revision 4 not found.`
> Adds: check that revision exist before promote call

- src/cli.rs
- src/commands/edge_app.rs
Adds --latest for promote. That flag can be used to promote the latest promoted revision.
Manually as we don't have tests for interaction with the app. get_latest_revision already had tests.
> Promote latest

- Cargo.toml
- src/cli.rs
- src/commands/edge_app.rs
- src/commands/edge_app_utils.rs
- src/commands/mod.rs
Reverts Screenly/cli#96
Not applied to settings/incorrectly does not allow empty optional fields (description/icon)
> Revert "Custom deserializers for empty string and settings type"

- src/commands/asset.rs
Issue: https://screenlyapp.slack.com/archives/C039ZN5AEN4/p1694427777457429
Tested: manually
> Fix: edge-app-file typo

- src/commands/edge_app.rs
- src/commands/edge_app_utils.rs
- src/commands/mod.rs
Refs https://phorge.wireload.net/T7492
Adds entrypoint optionally to the screenly.yml.
It is optional payload when version is created.
Though not tested yet as appserver part is not deployed yet.
> Adds: entrypoint optionally in the manifest - sent to a version.

- src/commands/edge_app.rs
- src/commands/mod.rs
Refs https://phorge.wireload.net/T7529
Throw proper error when app_id is missing on upload.
Other cases should be covered properly.
> Adds: proper error when app_id is missing on upload.

- src/commands/edge_app.rs
- src/commands/edge_app_utils.rs
Refs https://phorge.wireload.net/T7493
According to description from the task above, cli call is updated to pass all files signature and upload only ones, that was not copied on the server(returned as response from the call).
> Fix: copy_assets to version to be called on all files before upload.

- src/cli.rs
- src/commands/edge_app.rs
Moves `generate-mock-data` to a sub-command for `run`
- Unit tests pass after this change
- **Manual tests**
This is how `run` looks now: 
This are new messages in `cli` after this change:
> Generate mock data subcommand

- src/commands/edge_app.rs
- src/commands/edge_app_manifest.rs
- src/commands/edge_app_server.rs
Removes custom serializer. Simplifies data structure.
https://github.com/Screenly/cli/issues/119
All tests pass and `edge-app run` with hello world works in the browser..
> Remove custom deserializer

- README.md
- build.rs
- src/authentication.rs
Refs https://phorge.wireload.net/T7472
We want to freeze API URL during the building time.
Required for our integration tests and will be also convenient during development - building once, w/o commenting/uncommenting API_BASE_URL.
Also I decided not to provide url, but provide aliases during build time - local, stage or prod, prod being default of course.
build script is based on rust examples https://doc.rust-lang.org/cargo/reference/build-script-examples.html
`API_SERVER_NAME=local cargo build`
> Adds: build variable for api server url

- build.rs
We used to have `api.screenlyapp.com/api`, but we have now dropped the double API mention in the path
> Fixes API URL path

- .github/workflows/nix.yml
- .gitignore
- flake.lock
- flake.nix
Adds a `flake.nix` which enables the following
- Building `screenly-cli` as a nix package (just run `nix build .#screenly-cli` or `nix run .#screenly-cli`)
- A portable development shell will dependencies pre-packaged (`nix develop`)
- A package overlay for use on NixOS machines and other Nix package manager instances.
This PR also adds a workflow that builds that Nix package on pushes to `master` and pull requests.
It would be beneficial in the future if the `Cargo.lock` file was committed to the repository, but I've worked around this in the patch phase of the build.
None
Tested on a native NixOS machine, and on Ubuntu 22.04 running the nix package manager.
> Add Nix support

- action.yml
Currently, the status code is swallowed by the pipe. This brings back the correct exit code.
Resolves issue in https://github.com/Screenly/Playground/issues/154
> Fixes response code

- src/commands/edge_app.rs
- src/commands/edge_app_settings.rs
- src/commands/mod.rs
Refs https://phorge.wireload.net/T8070
As global setting requires a bit different payload (app_id instead of installation_id) - updated that in set_setting function.
For that - asks server if the setting is global - don't want to rely on the manifest file here.
Next pr will be about setting global secret.
> Adds: setting global setting

- src/commands/edge_app.rs
- src/commands/edge_app_manifest.rs
- src/commands/edge_app_settings.rs
- src/commands/edge_app_utils.rs
- src/commands/mod.rs
Refs https://phorge.wireload.net/T8231
Uses 4.1 API version, where we differentiated name and title. Basically what was previously an id(named title) is now a 'name'. Though it is not affecting yaml at all, cause title was ignored there totally before.
> Adds: 4.1 API update for title and name for settings.

- src/cli.rs
- src/commands/edge_app.rs
- src/commands/edge_app_utils.rs
- src/commands/mod.rs
When settings are missing in the yaml - prompt user to delete these missing settings.
Optionally accepts --delete-missing-settings=true/false to ignore prompt.
> Adds: deleting missing settings.

- Cargo.lock
- Cargo.toml
- Dockerfile
- action.yml
Releasing 0.2.6 version
Changes:
- Delete missing settings
- Entrypoint now pushed to installation instead of version
- Name of the installation from cli is now equal to app name instead of generic name.
> Adds: release 0.2.6

- src/commands/edge_app.rs
Adds: CI env var to ingore deleting missing settings.
In theory for next updates, all prompts should be silenced when CI=true is defined.
> Adds: CI env var to ignore deleting settings auto

- Cargo.lock
- Cargo.toml
- Dockerfile
- action.yml
Release 0.2.7
Changes:
- CI env variable to disable user prompt
- API_BASE_URL env var to override api url in the runtime
Ignore lint - we probably need to write our own clippy check.
> Release: 0.2.7

- src/commands/edge_app_server.rs
Ticket: https://phorge.wireload.net/T8625
Edits:
- secrets are merged into settings in Edge App emulator
> Fix: screenly.secrets merged into screenly.settings in 'screenly edge-app run'

- .github/workflows/lint.yml
- src/commands/edge_app.rs
- src/commands/edge_app_server.rs
- src/commands/mod.rs
Ticket: https://phorge.wireload.net/T8681
Edits:
- `screenly edge-app run` opens the URL in browser
It is tested only on Linux.
> Edits: 'edge-app run' open in browser

- README.md
This PR should simplify our README for reading. Right now It looks a bit heavy and messy. 
Also `USAGE` block has been replaced with a link to the list of commands. So if the Usage block contains any useful info that we want to keep, we need to update help for these commands.
I also plan to use the updated README for https://developer.screenly.io/. 
Thus, CLI documentation will be fully generated and based on docs from the repository.
> Edits: README.md

- .github/workflows/docs.yml
Edits
- Developer Portal deploy workflow will be triggered on push to master if `docs/CommandLineHelp.md` changed 
Example: https://github.com/Screenly/developer-portal/actions/runs/9892684905
> Added: trigger Developer Portal deploy workflow on docs changes

- src/commands/edge_app.rs
Revisions were created even if nothing changed when deploy called.
That was cause we don't use entrypoint in version anymore, but used it in comparison to check if new version to be created.
Removed entrypoint from the check.
> Fix: no entyrpoint in the versions.

- src/commands/edge_app_utils.rs
Detect settings changes code assumes the remote and local settings are sorted. Though it was not true for added extra settings - entrypoint and auth. Fixed that.
> Fix: sort settings in detect after adding special settings.

- src/commands/edge_app_utils.rs
- src/commands/manifest_auth.rs
Renames auth settings to have screenly_ prepended.
> Rename: auth setting prepended with screenly_

- src/commands/edge_app_manifest.rs
- src/commands/edge_app_settings.rs
When calling validate command, fails if there is a setting starting with 'screenly_' as it is now reserved names for settings.
> Adds: restrict 'screenly_*' names for settings on validation.

- src/cli.rs
- src/commands/edge_app.rs
- src/commands/edge_app_manifest.rs
- src/commands/edge_app_settings.rs
- src/commands/edge_app_utils.rs
- src/commands/mod.rs
Adds: validate instance manifest if it exists.
Validate entrypoint configuration between manifests.
> Adds: intervalidation of manifests for entrypoint

- Cargo.lock
Bumps the `time` rust dependency to 0.3.36. Without it, the `cli` package won't build with `rust > 1.80.0`, which was pointed out in https://github.com/NixOS/nixpkgs/issues/332957
https://github.com/NixOS/nixpkgs/issues/332957
Fairly naively - I bumped the dependency and checked the code still builds. I also ran `cargo test`, which completed successfully:
```
Finished `test` profile [unoptimized + debuginfo] target(s) in 30.90s
Running unittests src/main.rs (target/debug/deps/screenly-d041db5838078ffc)
running 115 tests
test authentication::tests::test_read_token_correct_token_is_returned ... ok
test authentication::tests::test_read_token_when_token_is_overridden_with_env_variable_correct_token_is_returned ... ok
test cli::tests::test_transform_edge_app_path_to_manifest_without_path_should …
```
> chore(deps): bump time to 0.3.36

- src/cli.rs
- src/commands/edge_app/app.rs
- src/commands/edge_app/utils.rs
- src/commands/mod.rs
Adds: MANIFEST_FILE_NAME env to override screenly.yml manifest file.
> Adds: env for overriding manifest file.

- Cargo.toml
- src/main.rs
Now debug calls are not stripped from release version, which in our case seems fine.
For release build INFO level is still a default, but could be overrdriven by default env var.
RUST_LOG is expected env for the log library, so no reason to replace it with our implementation --log-level or smth else.
`RUST_LOG=debug ../target/release/screenly edge-app list`
> Adds: ability to set debug logger level for release builds

- Cargo.lock
- Cargo.toml
- Dockerfile
- action.yml
Minor 1.0.1 release with debug logs accessible in release build via RUST_LOG=debug env var.
> Adds: release 1.0.1 including debug logs.

- action.yml
Tries: to upload logs as artifcat if cli command failed in execution.
> Try: to upload cli logs as artifact.

- Cargo.lock
- Cargo.toml
- Dockerfile
- action.yml
- src/commands/edge_app/utils.rs
> Bump cli version to 1.0.2

- src/commands/edge_app/server.rs
- src/commands/edge_app/utils.rs
Fixes browser failing to start on Windows due to incorrect 'start' command usage.
> Fix windows browser open command

- .github/workflows/release.yml
> Bump macos runner versions

- .github/workflows/actions.yml
- build.rs
- src/commands/edge_app/server.rs
The screenly.js file was being served with text/html Content-Type instead of application/javascript, causing browser console errors. This change:
- Updates server.rs to use application/javascript MIME type
- Adds test to verify correct Content-Type header is returned
- Fixes format string linting issue in build.rs
Resolves JavaScript MIME type console error in edge-app emulator.
#250
I have tested this locally and can confirm that the error is no longer visible in the console.log().
> fix: serve JavaScript with correct MIME type in edge-app run

- src/commands/playlist.rs
Fixed append failing when using on empty playlist. Added a unit test for that and manually tested
> Fix append not working with empty playlist
