- .github/workflows/rust.yml
Adds upload of artifacts to CI run.
N/A
N/A
N/A
> Adds artifact upload

- .github/workflows/rust.yml
- README.md
* Improves documentation
* Fixes CI artifact path
* Switch build to releases rather than debug
> Tweaks build flow and improves documentation

- src/commands.rs
- src/main.rs
Adds screen delete/add commands.
Added unit tests to make sure correct requests are sent.
https://ph.wireload.net/T6411
> Implement screen delete/add

- Cargo.toml
- src/authentication.rs
- src/commands.rs
- src/main.rs
Adds asset-related commands.
Upload progress bar:
PH T6405
Manually + unit tests
> Add asset commands

- .github/workflows/release.yml
- .github/workflows/rust.yml
Adds workflow for release.
-
Not yet.
Build and upload binaries on release action.
> Adds workflow for release.

- src/main.rs
> Use println for asset output so that it's usable with jq

- .github/workflows/release.yml
> Use unique name

- .github/workflows/release.yml
Fixes minor linting issue in release.yml.
> Minor release linting

- .github/workflows/release.yml
> Removed unused build matrix

- .github/workflows/release.yml
> Fix syntax

- src/authentication.rs
- src/main.rs
> Small cosmetic improvements.

- Cargo.toml
- src/commands.rs
- src/main.rs
> Bump version. Make tests get version programmatically.

- src/main.rs
> Fix "basic-auth" about message

- Cargo.toml
- Dockerfile
- src/main.rs
> New version

- Cargo.toml
- Dockerfile
> Bump version

- src/commands.rs
- src/main.rs
https://github.com/Screenly/cli/issues/41
> Tweak the way headers are set

- src/authentication.rs
- src/commands.rs
Previously missed that Status Codes had defined enum values. Using them where it's possible.
-
Unit tests still pass.
> Refactor status codes usage

- src/commands/edge_app.rs
Refs https://phorge.wireload.net/T7243
Set setting now sets global setting.
It either POST or PATCH if settings exists or not.
Also it requires installation to be there - so fetch or create it same way as in the upload func.
> Updates: set setting command to use global settings

- Cargo.toml
- src/commands/edge_app.rs
- src/commands/edge_app_utils.rs
Upload now does parallel upload and progress is displayed as number of files uploaded
> Parallel upload

- src/commands/edge_app.rs
- src/commands/edge_app_utils.rs
Refs https://phorge.wireload.net/T7303
Rename text to string for settings type.
> Updates: rename text to string for setting type.

- src/commands/mod.rs
> Increate timeout for copy-assets command

- data/index.html
- src/commands/edge_app.rs
Improves the Hello World edge-app
https://github.com/Screenly/cli/issues/64
Manually
> Edits: improved hello world app

- .yamllint.yml
- Cargo.toml
- action.yml
- src/authentication.rs
- src/cli.rs
- src/commands/asset.rs
- src/commands/edge_app.rs
- src/commands/mod.rs
- src/commands/screen.rs
- src/signature.rs
Quick fix for https://github.com/Screenly/cli/issues/61 and https://phorge.wireload.net/T7291. Tests for veryfying the `save_to_file` function and if the required fields are present will be done under https://phorge.wireload.net/T7350.
> Add -- at the start of created .yml file

- src/cli.rs
Exit with error when command failed
> Exit with error when command failed

- src/cli.rs
Just renames cli edge app update command to edge app rename
> Renames: update to rename

- src/commands/edge_app.rs
- src/commands/mod.rs
Column channels in the list versions.
Got data with postgrest embedding.
```
+----------+-----------------+-----------+-------------------+
| Revision | Description     | Published | Channels          |
+----------+-----------------+-----------+-------------------+
| 1        | Initial release | ✅        | stable, candidate |
+----------+-----------------+-----------+-------------------+
| 2        | Bug fixes       | ✅        |                   |
+----------+-----------------+-----------+-------------------+
```
> Adds: channels column to list versions

- src/commands/edge_app_server.rs
Fixes metadata not being under "metadata" key
Tests updated and manual
> Fix metadata not being in its own section

- .gitignore
- Cargo.toml
- src/cli.rs
- src/commands/edge_app.rs
- src/commands/edge_app_utils.rs
- src/commands/mod.rs
https://phorge.wireload.net/T7350
> Custom deserializers for empty string and settings type

- Cargo.toml
- Dockerfile
> Prepare release 0.2.0

- action.yml
> Update gh action app version

- src/commands/playlist.rs
Ticket: https://phorge.wireload.net/T6772
Description: See the topic
URLs:
- `/api/v4/playlist_items` -> `/api/v4/playlist-items`
> Edits: replaced all _ in v4 urls to -

- src/commands/edge_app_server.rs
Fixes wrapping array values with extra double quotes.
https://phorge.wireload.net/T7534
> Fixed: Array values are wrapped with double quotes

- Cargo.toml
- Dockerfile
- action.yml
As breaking changes(default_value constraints) released to prod, we need to release new cli version.
> Updates: revision to 0.2.1

- .github/workflows/release.yml
> CI release windows version

- .github/workflows/release.yml
Asset: https://github.com/Screenly/cli/releases/tag/test
Action: https://github.com/Screenly/cli/actions/runs/6822329559
Tested on Windows 11 (64bit)
> New: windows support on release workflow

- .github/workflows/release.yml
Test: https://github.com/Screenly/cli/actions/runs/6823001621/job/18556068565
> Edits: archive windows build with zip

- Cargo.toml
- Dockerfile
- action.yml
Release includes:
- Updates: required string can lack default_value. Updated undefined API to new settings API.
> Release: v0.2.3

- .github/workflows/nix.yml
- flake.nix
The build for macOS was subtly broken due to some missing frameworks. This PR addresses that and makes the build pass, but also adds a CI job to run the build on macOS alongside Ubuntu. I've also made the CI workflow run on a few more paths.
> Fix nix builds on macOS

- action.yml
Edits:
- Added output to action.yml (to get cli command's response)
> Added: cli_commands_response output to action.yml

- src/commands/edge_app.rs
Refs https://phorge.wireload.net/T8070
Update to set secret same as for the set setting for is_global secrets.
> Adds: setting global secret

- Cargo.lock
- Cargo.toml
- Dockerfile
- action.yml
> Release: version 0.2.4

- .github/workflows/release.yml
Updates: permissions for release
> Try: permissions for release

- README.md
Adds docs on how to release in the Readme
> Adds: release docs.

- Cargo.lock
- Cargo.toml
- Dockerfile
- action.yml
New 0.2.5 release.
Adds: proper setting title handling in the yaml.
> Makes: new 0.2.5 release.

- src/cli.rs
Some help texts were missing - added them.
> Adds: missing help texts

- .github/workflows/lint.yml
- src/authentication.rs
- src/commands/edge_app.rs
Adds env variable to change the API host.
> Adds: API_BASE_URL env var

- .github/workflows/actions.yml
- action.yml
Ticket: https://phorge.wireload.net/T8682
Screenshot:
> Edits: print cli command output in run-cli step

- src/commands/edge_app.rs
- src/commands/edge_app_manifest.rs
- src/commands/edge_app_settings.rs
- src/commands/edge_app_utils.rs
- src/commands/instance_manifest.rs
- src/commands/mod.rs
- **WIP**
- **WIP: Broken and compilable**
- **Fix manifest tests**
> New manifest wip

- src/cli.rs
- src/commands/edge_app.rs
- src/commands/mod.rs
Removes secrets list and set commands(all secret comands), and added functionality to the settings list/set.
> Merge: settings and secrets as just settings command.

- Cargo.lock
- Cargo.toml
- src/commands/edge_app.rs
- src/commands/edge_app_manifest.rs
- src/commands/edge_app_utils.rs
- src/commands/instance_manifest.rs
- **Instance manifest implementation**
- **Simplify tests**
> instance manifest

- src/commands/edge_app.rs
- src/commands/edge_app_manifest.rs
- **Start fixing tests**
- **Fix bugs and start reenabling tests**
> start fixing tests

- README.md
- flake.nix
* Adds instructions for installing Screenly CLI using Nix
* Updates homepage link in Nix package
> Adds Nix installation instructions

- src/commands/edge_app.rs
- src/commands/edge_app_manifest.rs
- src/commands/edge_app_settings.rs
- src/commands/edge_app_utils.rs
- src/commands/manifest_auth.rs
- src/commands/mod.rs
> Edge app support auth

- src/cli.rs
- src/commands/edge_app.rs
- src/commands/mod.rs
Removing instance_id argument from instance commands, and removed several deprecated functions.
> Removes: args from instance commands. Removes deprecated functions.

- src/cli.rs
- src/commands/edge_app.rs
Removes args from the edge apps commands.
> Removes: args from edge apps commands.

- src/commands/edge_app.rs
On instance update command now updates entrypoint properly.
> Fix: instance update updates entrypoint properly

- docs/EdgeApps.md
https://phorge.wireload.net/T8593
> Added Global Branding information

- src/commands/edge_app.rs
- src/commands/edge_app_utils.rs
Adds: instance.yml to ignore file list when uploading edge-app assets.
> Adds: instance.yml to ignore list

- Cargo.lock
- Cargo.toml
- Dockerfile
- action.yml
Fix: NixOs support by updating time package.
> Release: 0.2.8.

- docs/EdgeApps.md
> Update ready signal doc

- docs/EdgeApps.md
Ticket: https://phorge.wireload.net/T8838
Backend PR: https://github.com/Screenly/Screenly/pull/915/files
> Updated: Branding Settings List with dark ones

- src/cli.rs
- src/pb_signature.rs
> Fix ci checks

- src/commands/edge_app/utils.rs
> Disable some of the tests that might be flaky on macos
